#!/usr/bin/env python

import sys, os, re, subprocess
from subprocess import check_output

commit_msg_filepath = sys.argv[1]

with open(commit_msg_filepath, 'r') as f:
    content = f.read()
    pattern = r"^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|del|merge|update|hotfix|init)(\(.+\))?: .+$"
    if re.match(pattern, content):
        report = subprocess.run(["mango"], capture_output=True, text=True)
        if (report.returncode != 0):
            print("Something went wrong with coding style.")
            print(report.stdout)
            sys.exit(1)
        exit(0)
    else:
        print("Commit message does not match the pattern.")
        sys.exit(1)
